# Generated by Django 4.2.1 on 2023-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creation_date',
            field=models.DateField(default='2023-05-23'),
            preserve_default=False,
        ),
    ]
