# Generated by Django 4.2.1 on 2023-05-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_note_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
